version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    assignees:
      - hayashiki
    labels:
      - dependencies
      - go
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: Asia/Tokyo
#      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    assignees:
      - hayashiki
    labels:
      - dependencies
      - go
    schedule:
      time: "06:00"
      timezone: Asia/Tokyo
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
      - go
    schedule:
      time: "06:00"
      timezone: Asia/Tokyo
      interval: "weekly"
