linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - staticcheck
    - unconvert
    #   使ってない関数は許容
    #    - unused
    - varcheck
    - misspell

linters-settings:
  funlen:
    lines: 120
    statements: 50

run:
  skip-dirs:
    - bin
    - mock

issues:
  exclude:
    - Using the variable on range scope .* in function literal
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

service:
  golangci-lint-version: 1.43.0
