version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - ES_URL=${ES_URL}
      - TZ=Asia/Tokyo
    volumes:
      - db:/var/lib/mysql
      - ./logs:/var/log/mysql
#      必要あれば
#      - ./deployments/docker/mysql/my.cnf:/etc/mysql/local/conf.d/my.cnf
    ports:
      - "3306:3306"
volumes:
  db:
