name: Terraform Workflow
on:
  pull_request:
    paths:
      - ".github/workflows/terraform.yml"
      - "terraform/**"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [./terraform]

    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0-beta1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "272.0.0"
          service_account_key: ${{ secrets.PROD_GCP_CI_USER_KEY_BASE64 }}
          export_default_credentials: true
      - name: Terraform Format
        id: fmt
        run: terraform fmt -rescursive -check
        working-directory: ./terraform

      - name: Terraform Format
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform
